"""Stored AI report proposal and identity helpers."""

import hashlib
import json

from ..tools.files.html import sanitize_html
from .ai_report_process import ReportProcessValue


# @testable true
# @tests tests_unit/test_020h_ai_report_execution.py::test_run_report_retry_resumes_after_completed_create_without_duplicate
# @pair ai-report:idempotency
def proposal_fingerprint(proposal):
    canonical = json.dumps(
        proposal,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# @testable true
# @tests tests_unit/test_020a_ai_report_properties.py::test_ai_report_create_and_file_cleanup
# @tests tests_unit/test_020g_ai_report_actions_forms.py::test_run_report_adds_form_to_existing_page_with_undo
# @matrix ai-report : answer-html ask html-sanitization page-form proposal
class Proposal(ReportProcessValue):
    """Structured action proposal generated by AI."""

    _id = "proposal"

    @property
    # @testable infrastructure
    # @covered-by lagniappe/core/tools/ai/reporting/display/projector.py::ProposalDisplayProjector.display_actions
    def display_actions(self):
        from ..tools.ai.reporting.display import proposal_display_actions

        return proposal_display_actions(self)

    @property
    def answer_html(self):
        if not isinstance(self.value, dict):
            return None

        answer = self.value.get("answer_html")
        if not answer:
            return None

        return sanitize_html(answer)
