"""Stored AI report proposal and identity helpers."""

import hashlib
import json
from collections import Counter

from ..tools.files.html import sanitize_html
from .ai_report_process import ReportProcessValue


# @testable true
# @tests tests_unit/test_020h_ai_report_execution.py::test_run_report_retry_resumes_after_completed_create_without_duplicate
# @pair ai-report:idempotency
def proposal_fingerprint(proposal):
    canonical = json.dumps(
        proposal,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# @testable true
# @tests tests_unit/test_020a_ai_report_properties.py::test_ai_report_create_and_file_cleanup
# @tests tests_unit/test_020g_ai_report_actions_forms.py::test_run_report_adds_form_to_existing_page_with_undo
# @matrix ai-report : answer-html ask html-sanitization page-form proposal
class Proposal(ReportProcessValue):
    """Structured action proposal generated by AI."""

    _id = "proposal"

    # @testable true
    # @tests tests_unit/test_020a_ai_report_properties.py::test_proposal_action_summary_counts_actions_without_predicting_records
    # @tests tests_e2e/002_home/test_002j_home_tools.py::test_report_detail_runs_ready_report
    # @matrix ai-report : proposal action-counts
    @property
    def action_summary(self):
        maximum = None
        if self.entity.origin == "api":
            from ..tools.ai.external_api import MAX_PROPOSAL_ACTIONS

            maximum = MAX_PROPOSAL_ACTIONS
        return summarize_actions(self.value, maximum=maximum)

    @property
    # @testable infrastructure
    # @covered-by lagniappe/core/tools/ai/reporting/display/projector.py::ProposalDisplayProjector.display_actions
    def display_actions(self):
        from ..tools.ai.reporting.display import proposal_display_actions

        return proposal_display_actions(self)

    @property
    def answer_html(self):
        if not isinstance(self.value, dict):
            return None

        answer = self.value.get("answer_html")
        if not answer:
            return None

        return sanitize_html(answer)


# @testable false
# @covered-by lagniappe/core/properties/ai_report_proposal.py::Proposal.action_summary
# @reason the website and external receipts count the same saved action list
def summarize_actions(proposal, *, maximum=None):
    actions = (proposal or {}).get("actions", [])
    counts = Counter(action["type"] for action in actions)
    result = {"total": len(actions), "by_type": dict(sorted(counts.items()))}
    if maximum is not None:
        result["maximum"] = maximum
    return result
