"""Reusable text block constants for AI prompt generation rules and instructions."""

from .forms import (
    PAGE_FORM_SCHEMA_FORMAT,
    TASK_FORM_SCHEMA_FORMAT,
    PAGE_FORM_REQUIREMENTS,
    TASK_FORM_REQUIREMENTS,
    TASK_FORM_CONTENT_GUIDELINES,
    PAGE_FORM_CONTENT_GUIDELINES,
    FORM_AUTOFILL_RULES,
    SCHEMA_TYPE_GUIDELINES,
)

from .output import (
    JSON_OUTPUT_RULES,
    HTML_GENERATION_RULES,
    TEXT_OUTPUT_RULES,
    SAFETY_RULES,
)

from .images import (
    IMAGE_PROMPT_RULES,
)

from .context import (
    CONTEXT_USAGE_GUIDELINES,
    FORM_ENTITY_BOUNDARIES,
    LAGNIAPPE_WORKSPACE_CONCEPTS,
    SELECTED_TEXT_HANDLING,
    FILE_CONTEXT,
    ATTACHED_FILES_CONTEXT,
)

from .category import (
    CATEGORY_GENERATION_GUIDELINES,
    CATEGORY_OUTPUT_REQUIREMENTS,
)

from .project import (
    PROJECT_GENERATION_GUIDELINES,
    PROJECT_OUTPUT_REQUIREMENTS,
    PROJECT_COMPLEXITY_GUIDELINES,
)

from .pages import (
    PAGE_GENERATION_RULES,
    DOCUMENT_GUIDELINES,
    PAGE_GENERATION_OUTPUT_REQUIREMENTS,
    SUBMISSION_OUTPUT_REQUIREMENTS,
)

from .scheduling import (
    MONTHLY_SCHEDULING_PROMPT_RULES,
    MONTHLY_SCHEDULING_OUTPUT_REQUIREMENTS,
    YEARLY_SCHEDULING_PROMPT_RULES,
    YEARLY_SCHEDULING_OUTPUT_REQUIREMENTS,
    PERIODIC_SCHEDULING_PROMPT_RULES,
    PERIODIC_SCHEDULING_OUTPUT_REQUIREMENTS,
    REPORT_TASK_SCHEDULING_GUIDELINES,
)

from .summary import (
    SUMMARY_GENERATION_GUIDELINES,
)

from .schema_evolution import (
    SCHEMA_EVOLUTION_GUIDELINES,
)

from .organize import (
    ORGANIZE_ACTION_GUIDELINES,
    REPORT_PREFLIGHT_CHECKS,
    REPORT_OUTPUT_REQUIREMENTS,
    ORGANIZE_PLANNING_ACTIONS,
    ORGANIZE_PLANNING_CONCEPTS,
    ORGANIZE_PLANNING_OUTPUT,
    ORGANIZE_PLANNING_POLICY,
    ORGANIZE_PLANNING_PREFLIGHT,
    ORGANIZE_PLANNING_TOOLS,
)

__all__ = [
    # Forms
    "PAGE_FORM_SCHEMA_FORMAT",
    "TASK_FORM_SCHEMA_FORMAT",
    "PAGE_FORM_REQUIREMENTS",
    "TASK_FORM_REQUIREMENTS",
    "TASK_FORM_CONTENT_GUIDELINES",
    "PAGE_FORM_CONTENT_GUIDELINES",
    "FORM_AUTOFILL_RULES",
    "SCHEMA_TYPE_GUIDELINES",
    # Output
    "JSON_OUTPUT_RULES",
    "HTML_GENERATION_RULES",
    "TEXT_OUTPUT_RULES",
    "SAFETY_RULES",
    # Images
    "IMAGE_PROMPT_RULES",
    "IMAGE_SEARCH_RULES",
    "PAGE_IMAGE_SEARCH_OUTPUT_REQUIREMENTS",
    # Context
    "CONTEXT_USAGE_GUIDELINES",
    "FORM_ENTITY_BOUNDARIES",
    "LAGNIAPPE_WORKSPACE_CONCEPTS",
    "SELECTED_TEXT_HANDLING",
    "FILE_CONTEXT",
    "ATTACHED_FILES_CONTEXT",
    # Category
    "CATEGORY_GENERATION_GUIDELINES",
    "CATEGORY_OUTPUT_REQUIREMENTS",
    # Project
    "PROJECT_GENERATION_GUIDELINES",
    "PROJECT_OUTPUT_REQUIREMENTS",
    "PROJECT_COMPLEXITY_GUIDELINES",
    # Pages
    "PAGE_GENERATION_RULES",
    "DOCUMENT_GUIDELINES",
    "PAGE_GENERATION_OUTPUT_REQUIREMENTS",
    "SUBMISSION_OUTPUT_REQUIREMENTS",
    # Scheduling
    "MONTHLY_SCHEDULING_PROMPT_RULES",
    "MONTHLY_SCHEDULING_OUTPUT_REQUIREMENTS",
    "YEARLY_SCHEDULING_PROMPT_RULES",
    "YEARLY_SCHEDULING_OUTPUT_REQUIREMENTS",
    "PERIODIC_SCHEDULING_PROMPT_RULES",
    "PERIODIC_SCHEDULING_OUTPUT_REQUIREMENTS",
    "REPORT_TASK_SCHEDULING_GUIDELINES",
    # Summary
    "SUMMARY_GENERATION_GUIDELINES",
    # Schema evolution
    "SCHEMA_EVOLUTION_GUIDELINES",
    # Organize
    "ORGANIZE_ACTION_GUIDELINES",
    "REPORT_PREFLIGHT_CHECKS",
    "REPORT_OUTPUT_REQUIREMENTS",
    "ORGANIZE_PLANNING_ACTIONS",
    "ORGANIZE_PLANNING_CONCEPTS",
    "ORGANIZE_PLANNING_OUTPUT",
    "ORGANIZE_PLANNING_POLICY",
    "ORGANIZE_PLANNING_PREFLIGHT",
    "ORGANIZE_PLANNING_TOOLS",
]
