const CONFIG = {
	FORM_COMPONENTS: [
		{ type: "input", label: "Input" },
		{ type: "link", label: "Link" },
		{ type: "location", label: "Location" },
		{ type: "textarea", label: "Text" },
		{ type: "checkbox", label: "Checkbox" },
		{ type: "radio", label: "Radio Group" },
		{ type: "select", label: "Select" },
		{ type: "table", label: "Table" },
		{ type: "signature", label: "Signature" },
		{ type: "html", label: "Document" },
		{ type: "status", label: "Status" },
	],
	PAGE_COMPONENTS: [
		{ type: "input", label: "Input" },
		{ type: "link", label: "Link" },
		{ type: "location", label: "Location" },
		{ type: "textarea", label: "Text" },
		{ type: "bookmark", label: "Bookmark" },
		{ type: "checkbox", label: "Checkbox" },
		{ type: "radio", label: "Radio Group" },
		{ type: "select", label: "Select" },
		{ type: "table", label: "Table" },
	],
	INPUTS: [
		{ type: "text", name: "Text" },
		{ type: "tel", name: "Phone Number" },
		{ type: "number", name: "Number" },
		{ type: "email", name: "Email" },
		{ type: "date", name: "Date" },
		{ type: "time", name: "Time" },
	],
	TABLE_COLUMNS: [
		{ type: "text", name: "Text" },
		{ type: "tel", name: "Phone Number" },
		{ type: "number", name: "Number" },
		{ type: "email", name: "Email" },
		{ type: "date", name: "Date" },
		{ type: "time", name: "Time" },
		{ type: "out", name: "External Link" },
		{ type: "in", name: "Internal Link" },
		{ type: "checkbox", name: "Checkbox" },
	],
	LINKS: [
		{ type: "out", name: "External" },
		{ type: "in", name: "Internal" },
	],
	PRESENTATION_DEFAULTS: {
		bookmark: { title: "Bookmark" },
		checkbox: { title: "Checkbox" },
		html: { title: "Rich Text" },
		input: { title: "Input", input: "text" },
		link: { title: "Link", location: "out" },
		location: { title: "Location" },
		radio: { title: "Radio Group" },
		select: { title: "Select" },
		signature: { title: "Signature" },
		status: { title: "Status" },
		table: { title: "Table" },
		textarea: { title: "Text" },
	},
	DEFAULT_SETTINGS: {
		input: [
			"title",
			"placeholder",
			"visibility",
			"input",
			"required",
			"deleteButton",
		],
		link: ["title", "visibility", "required", "location", "deleteButton"],
		location: [
			"title",
			"placeholder",
			"visibility",
			"required",
			"deleteButton",
		],
		textarea: [
			"title",
			"placeholder",
			"visibility",
			"required",
			"deleteButton",
		],
		bookmark: ["title", "deleteButton"],
		checkbox: ["title", "visibility", "checked", "required", "deleteButton"],
		radio: ["title", "visibility", "options", "required", "deleteButton"],
		select: [
			"title",
			"placeholder",
			"visibility",
			"options",
			"multiple",
			"required",
			"deleteButton",
		],
		html: ["title", "visibility", "editor", "deleteButton"],
		signature: ["title", "required", "deleteButton"],
		status: ["title", "status", "deleteButton"],
		table: ["title", "columns", "visibility", "deleteButton"],
	},
};

export { CONFIG };
